### ISSUE TITLE
Question about scale factor

### ISSUE THREAD

**Issue by izuna385** [sfzhou5678/PolyEncoder#1]
Thanks for uploading codes. I'm going to run them.

In 
https://github.com/sfzhou5678/PolyEncoder/blob/master/model/encoder.py#L59
there's a (scaling?) factor, 5.
I can't find out what this means. If you'd know something about this, I'd appreciate it.

**Comment by sfzhou5678** [comment]
Sorry for the late reply. 
The parameter γ=5.0 is a smoothing factor for softmax, so actually the softmax function in code is:
np.exp(γX) / np.sum(np.exp(γX), axis=1). This softmax function is also known as "softmax with temperature". The original DSSM paper (https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/cikm2013_DSSM_fullversion.pdf) also use this trick.
Please feel free to let me know if you have any questions.

**Comment by sfzhou5678** [comment]
> Thanks for uploading codes. I'm going to run them.
> 
> In
> https://github.com/sfzhou5678/PolyEncoder/blob/master/model/encoder.py#L59
> there's a (scaling?) factor, 5.
> I can't find out what this means. If you'd know something about this, I'd appreciate it.

Sorry for the late reply.
The parameter γ=5.0 is a smoothing factor for softmax, so actually the softmax function in code is:
np.exp(γX) / np.sum(np.exp(γX), axis=1). This softmax function is also known as "softmax with temperature". The original DSSM paper (https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/cikm2013_DSSM_fullversion.pdf) also use this trick.
Please feel free to let me know if you have any questions.

**Comment by izuna385** [comment]
Thanks for your detailed information and introducing interesting techniques! I'll check them.
